//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.06 at 03:52:59 PM KST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://hokuma.pro", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package toby.tutorial.user.sqlservice.jaxb;
